micronaut:
  application:
    name: micronaut-discovery
  metrics:
    enabled: true
    export:
      newrelic:
        enabled: true
        apiKey: ${NEWRELIC_API_KEY}
        accountId: ${NEWRELIC_ACCOUNT_ID}
        step: PT1M
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
ribbon:
  VipAddress: test
  ServerListRefreshInterval: 2000
eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}
kafka.bootstrap.servers: localhost:9092
elasticsearch.httpHosts: '"http://localhost:9200,http://127.0.0.2:9200"'
jpa.default.properties.hibernate.hbm2ddl.auto: update
hystrix.stream.enabled: false
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
redis:
  uri: redis://localhost
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
