name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true # optional (default = false)