name: Test Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: check
        run: ./gradlew check
      - name: generate report
        run: ./gradlew jacocoTestReport
      - name: upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
        
